# See https://github.com/typesafegithub/github-actions-typing
inputs:
  context:
    type: enum
    allowed-values:
      - workflow
      - git
  images:
    type: list
    separator: '\n'
    list-item:
      type: string
  tags:
    type: list
    separator: '\n'
    list-item:
      type: string
  flavor:
    type: list
    separator: '\n'
    list-item:
      type: string
  labels:
    type: list
    separator: '\n'
    list-item:
      type: string
  sep-tags:
    type: string
  sep-labels:
    type: string
  bake-target:
    type: string
